#!/usr/bin/env php
<?php

/**
 * Delete user files.
 * 
 * $ scripts/clean [search_pattern] [...]
 *
 */

function pattern_match($str, $patterns) {
  $patterns = implode("|", array_map('preg_quote', $patterns));
  return preg_match("/(" . $patterns . ")/i", $str);
}

define('DS', DIRECTORY_SEPARATOR);
define('ROOT', realpath(dirname(__FILE__) . DS . "..") . DS);
$file_list = Array(
  'Controllers/*',
  'Views/*',
  'Models/*',
  'stylesheets/*',
  'javascripts/*'
);

$all = false;

$patterns = array_slice($argv, 1);


foreach($file_list as $file) {
  $file = ROOT . $file;
  $files = glob($file);
  if(is_array($files)) {
    foreach($files as $del_file) {
      if(pattern_match($del_file, $patterns)) {
        if(is_file($del_file)) {
          $yes = $all;
          if(!$all) {
            echo "delete file $del_file ? (y|n|a|q) ";
            $handle = fopen("php://stdin", "r");
            $out = fgets($handle, 80);
            fclose($handle);
            switch($out) {
              case "a\n":
                $yes = $all = true;
                break;
              case "y\n":
                $yes = true;
                break;
              case "q\n":
                exit;
              default:
                break;
            }
            if($yes) {
              echo "rm    '$del_file'\n";
              unlink($del_file);
            }
          }
        } else if(is_dir($del_file)) {
          echo "DIR: $del_file\n";
          if(@rmdir($del_file)) {
            echo "rmdir '$del_file'\n";
          }
        }
      }
    }
  }
}

touch("stylesheets/application.css");
touch("javascripts/application.js");
file_put_contents("Helpers/ApplicationHelper.php", <<<APPLICATION_HELPER
<?php

namespace Void;

class ApplicationHelper extends HelperBase {
}
APPLICATION_HELPER
);

file_put_contents("Controllers/ApplicationController.php", <<<APPLICATION_CONTROLLER
<?php

namespace Void;

abstract class ApplicationController extends ControllerBase {
}
APPLICATION_CONTROLLER
);

@mkdir("Views/layout");
touch("Views/layout/application.tpl");
